language: python
python:
- '3.6'
- '3.5'
services:
- postgresql
env:
- DJANGO=2.0 DB=postgres
global:
- PGPORT=5432
before_install:
- cd decide
install:
- pip install -r ../requirements.txt
before_script:
- cp local_settings.example.py local_settings.py
- psql -c "create user decide with password 'decide'"
- psql -c "create database decide owner decide"
- python manage.py migrate
script:
- python manage.py test
addons:
  postgresql: '9.6'
jobs:
  include:
  - stage: deploy
    script: skip
    before_deploy:
    - cd ..
    deploy:
      provider: heroku
      api_key:
      secure: djFXY+Sobpp1Jvk5/i+KrJg1gHQLOR7U4uIPxV42Tw79GV7QijAgv/4v6TQnSkQU7uwDV3iPlI9Xti1Dpy1Pem9oq4FuKXktutQKSwae7qTKGbCnGnXEcmFveRJqzsHCPHwgmeXLBzrQcOYumHwFI7NDoAIzPFqjgzRs3W8mDMpRixdxmlKUxR5oyfjgqwoFMuF4Is3lVPvHeYlruhkeCAzCVHFUCB/hmdS+vSHMZ75kXhubDZB8OAHTz4S2QuxwWGS7tNa20pS39b0oNT+tSnVL7hjJR4OI0uG3Nmf8YW5SRZTUVJfIBz7ymEoo52Q3i2oYEM7pBeeSh8BsuwTlZsRSRE4MgW2pP4rtDFkd0Sgv6DW3GxTfDIM7slE9NbIVJhr0nGHSqMwfFbavDDk10v8x7M9IwXLFSpmFpaTYlikC6cmVubWLNXHxnrKm45MraZxTXPo/H/uOx2QlaluTkDsCjw1xx7wYTMcZXM7922dlV8pLp4R4wdK6WcD3sdihdrZvLlVwlCXeGj6WyUjxsGFfoYytU0KsTI7zDyzyH7XqSvtF7nSlmpgyOhyJCN4jQgbe48kj6FLoIv5Lw+H91SUwg8vjAOlm+eqrGHtxbdff5gS0/Kio9+IVCWB2efy9ajLiuH6KsAwTwp4RDDYntHTdjCUSVjAboAqrEypAgz8=
      app: decide-examen-ivan

